CREATE DATABASE IF NOT EXISTS tp2_ejercicio1;
USE tp2_ejercicio1;

CREATE TABLE IF NOT EXISTS rectangulos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lado1 DECIMAL(10, 2) NOT NULL,
    lado2 DECIMAL(10, 2) NOT NULL,
    perimetro DECIMAL(10, 2) NOT NULL,
    superficie DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);